apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressjs-backend-development
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: expressjs-backend
      env: dev
  template:
    metadata:
      labels:
        app: expressjs-backend
        env: dev
    spec:
      containers:
      - name: expressjs-backend
        imagePullPolicy: Always
        image: btlcr001.azurecr.io/nestjsbackend
        ports:
        - containerPort: 5000
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: expressjs-backend-development
spec:
  selector:
    app: expressjs-backend
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
    - protocol: TCP
      port: 81
      targetPort: 3000
  type: LoadBalancer 
