apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressjs-backend-development
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: expressjs-backend
      env: dev
  template:
    metadata:
      labels:
        app: expressjs-backend
        env: dev
    spec:
      containers:
      - name: expressjs-backend
        imagePullPolicy: Always
        image: btlcr001.azurecr.io/expressjsbackend
        ports:
        - containerPort: 3030
        - containerPort: 4040
        - containerPort: 3001
        - containerPort: 3002
        - containerPort: 3003

---
apiVersion: v1
kind: Service
metadata:
  name: expressjs-backend-development
spec:
  selector:
    app: expressjs-backend
    env: dev
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3030
    - name: http-alts
      protocol: TCP
      port: 81
      targetPort: 4040
    - name: http-user
      protocol: TCP
      port: 82
      targetPort: 3001
    - name: http-admin
      protocol: TCP
      port: 83
      targetPort: 3002
    - name: http-administrator
      protocol: TCP
      port: 84
      targetPort: 3003
  type: LoadBalancer

