apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressjs-backend-development
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: expressjs-backend
      env: dev
  template:
    metadata:
      labels:
        app: expressjs-backend
        env: dev
    spec:
      containers:
      - name: expressjs-backend
        imagePullPolicy: Always
        image: btlcr001.azurecr.io/expressjsbackend
        ports:
        - containerPort: 4040
        - containerPort: 3030
        - containerPort: 3032
        - containerPort: 3033

---
apiVersion: v1
kind: Service
metadata:
  name: expressjs-backend-development
spec:
  selector:
    app: expressjs-backend
    env: dev
  ports:
    - name: backend
      protocol: TCP
      port: 81
      targetPort: 4040
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: 3032
    - name: frontend-admin
      protocol: TCP
      port: 83
      targetPort: 3032
    - name: frontend-administrator
      protocol: TCP
      port: 84
      targetPort: 3033
  type: LoadBalancer

