apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressjs-backend-development
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: expressjs-backend
      env: dev
  template:
    metadata:
      labels:
        app: expressjs-backend
        env: dev
    spec:
      containers:
      - name: expressjs-backend
        imagePullPolicy: Always
        image: btlcr001.azurecr.io/expressjsbackend
        ports:
        - containerPort: 3030
        - containerPort: 4040

---
apiVersion: v1
kind: Service
metadata:
  name: expressjs-backend-development
spec:
  selector:
    app: expressjs-backend
    env: dev
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3030
    - name: http-alt
      protocol: TCP
      port: 81
      targetPort: 4040
  type: LoadBalancer

